language: node_js
os:
  - linux
dist: xenial
before_script:
  - npm install jasmine winston
node_js:
  - "8"
  - "10"
deploy:
  provider: npm
  edge: true
  email: software@pod-point.com
  on:
    branch: master
    tags: true
    repo: Pod-Point/winston-kinesis-transport
